### PR TITLE
FIX: EOF not being properly reported

### LINKED ISSUE #47: EOF not being sent
I noticed something a bit weird while I was testing the following code on the browser:

```c
#define CHUNK_SIZE 8

char *get_stdin(void) {
  size_t size = CHUNK_SIZE;
  char *buf = malloc(size + 1);
  char *ptr = buf;
  if (buf == NULL) {
    perror("Allocation failed");
    return NULL;
  }
  int bytes_read = 0;

  while ((bytes_read = read(STDIN_FILENO, ptr, CHUNK_SIZE)) > 0) {
    void *new_data = realloc(buf, size + CHUNK_SIZE);
    if (new_data == NULL) {
      perror("Allocation failed");
      return NULL;
    }
    size += CHUNK_SIZE;

    buf = new_data;
    ptr = buf + (ptr - buf) + bytes_read;
  }

  *ptr = '\0';

  return buf;
}
```

Whenever I hit ctrl-D to finish input, the `read` function would return -1 without setting errno and the last bytes since the last chunk are discarded.

Any help would be appreciated, I am trying to figure out the root cause right now.

### PR DESCRIPTION
**Pull request by leath-dub**
fixes #47. PLEASE TEST as I am very new to wasm and emscripten as well as JS itself :). I found that two 1006 codes were raised where EOF should have occurred and based on that just patched `fd_read` to handle that case and report a read of `0`.

### CODE REVIEW

File: emscripten-pty.js [hunk 1]
```diff
@@ -180,7 +180,13 @@ Object.assign(Lib, {
             PTY_waitForReadable((type) => {
                 switch (type) {
                     case 0: /* ready */
-			wakeUp(xterm_pty_old_fd_read(fd, iov, iovcnt, pnum));
+                        const inner = xterm_pty_old_fd_read(fd, iov, iovcnt, pnum);
+                        if (inner == {{{ 1000 + cDefs.EAGAIN }}}) {
```
Comment (mame) [inline emscripten-pty.js:184]:
```suggestion
                        if (inner == {{{ 1000 + cDefs.EAGAIN }}}) {
                          // Despite the fact that we are in the readable state,
                          // TTY.read returned our variant of EAGAIN again.
                          // This means that a readable state was due to EOF.
                          // Therefore, we return 0 to indicate that
                          // it has successfully read 0 bytes (i.e., EOF).
```

**Comment by mame** [comment]
Thank you! It took time for me to understand the problem and your change. I think it makes sense.

Let me just add a comment. I will merge with this soon. I hope to release it the weekend.

**Comment by mame** [comment]
Just FYI: I have published xterm-pty 0.11.0 with your fix. Thanks again!
